package:
  name: pyccl
  version: v0.2.1

source:
  git_url: https://github.com/EiffL/CCL.git
  git_rev: conda

requirements:
  host:
    - python
    - setuptools
    - cmake

  run:
    - python

build:
  number: 0
  script: 'python setup.py install'
